language: php
php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"

matrix:
  include:
    - php: "5.3"
      dist: precise

branches:
  only:
    - devel
    - master

before_script:
  - wget -O phpunit.phar https://phar.phpunit.de/phpunit-4.8.phar

script:
  - php phpunit.phar --version
  - php phpunit.phar -v -c tests/phpunit.xml

notifications:
  email:
    recipients:
      - serbanghita@gmail.com
    on_success: never
    on_failure: always
  slack:
    rooms:
      - mobiledetect:in9qB4EvOrdR5v1E8V0nNqsJ#general
  irc:
    channels:
      - "asimov.freenode.net#mobiledetect"
    template:
      - "%{repository} (%{commit}): %{message}. Build details: %{build_url}"
      - "%{author} said %{commit_subject}. See %{compare_url}"
