language: php
php:
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"

branches:
  only:
    - devel-3

script:
  - phpunit --configuration phpunit.xml.dist --coverage-text

notifications:
  email: false

install:
  - composer install
